version: "3"

services:
  oauth-server:
    build: ./
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
  
  mongo:
    image: mongo:3.6
    ports: 
      - "27017:27017"
    volumes:
      - ~/data:/data
